### ISSUE TITLE
Runtime Error in Cube.py

### ISSUE THREAD

**Issue by HSG88** [Charterhouse/pysnark#1]
Hi, 
I have been trying to run the first example cube.py, but I got this error

_python cube.py 3_

**Traceback (most recent call last):
  File "cube.py", line 40, in <module>
    inv = Var(int(sys.argv[1]), "in")
  File "/usr/local/lib/python2.7/dist-packages/pysnark/runtime.py", line 93, in inited_
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pysnark/runtime.py", line 319, in __init__
    vc_ctr[vc_ctx] += 1
KeyError: None**

**Comment by meilof** [comment]
I think this should be fixed by [this commit](https://github.com/Charterhouse/pysnark/commit/47a1a2c4d11db75c6d5d25bf36a08d23b8dd4814). Could you update your Git repository and check whether the problem is still here?

**Comment by HSG88** [comment]
Thanks, it is working now.
