### ISSUE TITLE
wrong proof is verified correctly!!

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [Charterhouse/pysnark#4]
I follow "readme"  and as a prover I changed the cube.py to calculate the 2*cube(in) to check if the verifier can recognize the inconsistency between third party code and prover cod.but surprisingly the verifier verified it correctly.what is the problem here?? prover can run a code diffrent from the code that third party provided and at the same time convince the verifier that he/she has done the right calculation.

**Comment by meilof** [comment]
You're right, thanks for reporting! There were a couple of problems that caused this: output values were not correctly checked and key generation was not randomized so that old evaluation keys could be used. Both should be fixed now.

**Comment by meilof** [comment]
I just saw I put the fixes in my personal fork https://github.com/meilof/pysnark that is otherwise the same as the Charterhouse one. If this indeed fixes your problem I can ask them to integrate the fix into their repository.

**Comment by markspanbroek** [comment]
Hi @meilof, you have admin rights on this repo. You should be able to integrate the fix into this repo. Either by creating a pull request and accepting it yourself, or by directly pushing to this repo.

Let me know if you run into any trouble and I'll try to help.

**Comment by meilof** [comment]
OK, merged the bug fix here. @Mahsa-Bastankhah, does this indeed solve your problem?

**Comment by Mahsa-Bastankhah** [comment]
> OK, merged the bug fix here. @Mahsa-Bastankhah, does this indeed solve your problem?

**Comment by Mahsa-Bastankhah** [comment]
I used the new version and tested again the case that I mentioned in my first comment. now during verification this is printed :  
"Reading QAP vk: pysnark_vk_main
Verifying main (pysnark_vk_main) *** divisibility check failed
1"
isn't it supposed to print 0 (false) when the prover has executed a different code and as a result ,provided wrong proof and value?
why it is still printing 1(true)?

**Comment by Mahsa-Bastankhah** [comment]
I faced another problem and I appreciate if you help me figure it out.
I used pysnark module so the prover can prove that he/she has preimage of a hash value without revealing the preimage.
I wrote this simple code for third party:
"""""""""""""""""""""
x = int(input())
s = sha256()
s.update(str(x))
Var(int(s.hexdigest(),16), 'commit')
"""""""""""""""""""""""""

and I executed different code as prover to check if verifier can realize that the prover is cheating or not.
here is prover code : 
""""""""""""
x = int(input())
s = sha256()
s.update(str(x))
Var(int(s.hexdigest(),16) + 10, 'commit') 
"""""""""""""""""
and at the end verifier verified it as true.
in this case prover doesn't know the preimage of "int(s.hexdigest(),16) + 10" but still can convince the verifier that she knows it!!! 
am I using the module wrongly or  I misunderstood something?

**Comment by meilof** [comment]
I agree this 

> I used the new version and tested again the case that I mentioned in my first comment. now during verification this is printed :
> "Reading QAP vk: pysnark_vk_main
> Verifying main (pysnark_vk_main) *** divisibility check failed
> 1"
> isn't it supposed to print 0 (false) when the prover has executed a different code and as a result ,provided wrong proof and value?
> why it is still printing 1(true)?

I agree this is a bit confusing. Made a separate issue of this.

**Comment by meilof** [comment]
> I faced another problem and I appreciate if you help me figure it out.
> I used pysnark module so the prover can prove that he/she has preimage of a hash value without revealing the preimage.
> I wrote this simple code for third party:
> """""""""""""""""""""
> x = int(input())
> s = sha256()
> s.update(str(x))
> Var(int(s.hexdigest(),16), 'commit')
> """""""""""""""""""""""""
> 
> and I executed different code as prover to check if verifier can realize that the prover is cheating or not.
> here is prover code :
> """"""""""""
> x = int(input())
> s = sha256()
> s.update(str(x))
> Var(int(s.hexdigest(),16) + 10, 'commit')
> """""""""""""""""
> and at the end verifier verified it as true.
> in this case prover doesn't know the preimage of "int(s.hexdigest(),16) + 10" but still can convince the verifier that she knows it!!!
> am I using the module wrongly or I misunderstood something?

PySNARK can only verify computations that you perform on variables that are imported into the runtime, e.g., by using the Var() constructor. So you should first import the values and then perform a computation on them. For hashing, see the example of https://github.com/meilof/pysnark/blob/master/examples/ggh/hashsnark.py. This uses the GGH hash function that should be much more efficient in the verifiable computation context than the SHA256 hash. There, what happens is:

    ins = [Var(x) for x in hexin]
    outs = ggh_hash(ins)
    print "out", len(outs), outs[:10], outs[-10:]

So first the regular array "hexin" is imported into PySNARK by making an array "ins" of PySNARK variables and then the hash is computed. In this case, the computation of the hash is verified for correctness.

Hope that helps.

**Comment by Mahsa-Bastankhah** [comment]
but prover has to distribute pysnark_values to verifier and in involves elements of "hexin" so the prover can't keep the preimage hidden!

**Comment by meilof** [comment]
Not if you provide True as second argument to the Var function: Var(..., True)

**Comment by Mahsa-Bastankhah** [comment]
thanks for your answer.
I changed my code as you told to : 
`
x = int(input())
Var(x,True)
s = sha256()
s.update(str(x))
Var(int(s.hexdigest(),16), 'commit')

`

and the code that prover runs is : 
`
x = int(input())
Var(x,True)
s = sha256()
s.update(str(x))
Var(int(s.hexdigest(),16)+10, 'commit')

`

so in this case the prover doesn't know the preimage of  "int(s.hexdigest(),16)+10" but the verifier still outputs TRUE.

**Comment by meilof** [comment]
You should perform the computation on the result of Var(x,True), not on x itself. x itself is still just a number, so hashing it will not be performed using verifiable computation E.g., compute my_sha256(Var(x,True)) where my_sha256 is an implementation of sha256 that works on verifiable computation variables
